# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eb7f95a7ca451d194caadee9fc763e41c663e8aa2523699637964bcde6aafaa1ae38492b00d5e6a0545f66c14077f2ff8749197a586c46190cdcb86fd53cf8e

test:
  secret_key_base: 812119a3c5a9c7973986f230036a426d0a8d00d39d395c3b5810520c2e50895b5209d51087e636c498930e92f137dca05fa0d2d9c5e47da0d50934f5e5d8031e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
